feat: security scan of Docker images using Snyk

diff --git a/.github/workflows/snyk-scan.yml b/.github/workflows/snyk-scan.yml
--- a/.github/workflows/snyk-scan.yml
+++ b/.github/workflows/snyk-scan.yml
@@ -60,12 +60,15 @@ jobs:
           snyk-api-results.json
           snyk-gateway-results.json
 
+    - name: Ensure Security Label Exists
+      run: |
+        gh label create security --color FF0000 --description "Security related issues" || echo "Label already exists"
+
     - name: Create GitHub Issues for Vulnerabilities
       if: always()
       run: |
         for file in snyk-api-results.json snyk-gateway-results.json; do
           if [ -f "$file" ]; then
-            echo "Found $file"
             vulnerabilities=$(jq -r '.vulnerabilities[] | @base64' $file)
             for vulnerability in $vulnerabilities; do
               _jq() {
@@ -74,7 +77,7 @@ jobs:
               title="SNYK: $(_jq '.title')"
               description="## Description\n$(_jq '.description')\n\n## Info\n$(_jq '.url')\n\n## Severity\n$(_jq '.severity')\n\n## Introduced through\n$(_jq '.from | join(", ")')\n\n## Remediation\n$(_jq '.remediation')"
               echo "Creating issue: $title"
-              gh issue create --title "$title" --body "$description" --label "security"
+              gh issue create --title "$title" --body "$description" --label "security" || echo "Failed to create issue: $title"
             done
           else
             echo "File $file not found"
